apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "harbor-snyk-scanner.fullname" . }}
  labels:
    {{- include "harbor-snyk-scanner.labels" . | nindent 4 }}
    {{- include "scanner.labels" . | nindent 4 }}
  annotations:
    {{- include "scanner.annotations" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "harbor-snyk-scanner.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "harbor-snyk-scanner.selectorLabels" . | nindent 8 }}
        {{- include "scanner.labels" . | nindent 8 }}
      annotations:
        {{- include "scanner.annotations" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --snyk.integration-id={{ .Values.settings.snykIntegrationID }}
            - --snyk.organisation-id={{ .Values.settings.snykOrganisationID }}
            - --log.format={{ .Values.settings.logFormat }}
            - --log.level={{ .Values.settings.logLevel }}
          ports:
            - name: http-api
              containerPort: 8080
              protocol: TCP
            - name: http-metrics
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http-api
          readinessProbe:
            httpGet:
              path: /health
              port: http-api
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
