apiVersion: v1
kind: Service
metadata:
  name: {{ include "harbor-snyk-scanner.fullname" . }}
  labels:
    {{- include "harbor-snyk-scanner.labels" . | nindent 4 }}
    {{- include "scanner.labels" . | nindent 4 }}
  annotations:
    {{- include "scanner.annotations" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http-api
      protocol: TCP
      name: http-api
    - port: 8081
      targetPort: http-metrics
      protocol: TCP
      name: http-metrics
  selector:
    {{- include "harbor-snyk-scanner.selectorLabels" . | nindent 4 }}
