---
apiVersion: v1
kind: Service
metadata:
  name: harbor-snyk-scanner
  labels:
    app: harbor-snyk-scanner
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http-api
      protocol: TCP
      name: http-api
    - port: 8081
      targetPort: http-metrics
      protocol: TCP
      name: http-metrics
  selector:
    app: harbor-snyk-scanner
